export type RBACReason =
  | 'ROLE_NOT_ASSIGNED'
  | 'PERMISSION_DENIED'
  | 'FEATURE_NOT_REGISTERED'
  | 'ACTION_NOT_REGISTERED'
  | 'ASSIGNMENT_NOT_FOUND'
  | 'ASSIGNMENT_SCOPE_MISMATCH'
  | 'ROLE_CEILING_VIOLATION'
  | 'CLIENT_FORBIDDEN'
  | 'OWNER_ONLY_ACTION';
// RBAC Reason Codes
// No implementation. No runtime logic.
