export const ASSIGNMENT_INVARIANTS = {
  UNIQUE: true,
  NO_CLIENT_ASSIGNMENTS: true,
  NO_IMPLICIT_ESCALATION: true,
  NO_WILDCARDS: true,
  NO_ROLE_CEILING_VIOLATION: true,
  EXPLICIT_ESCALATION: true,
  ATOMIC_ASSIGNMENT: true,
  NO_DUPLICATE_ASSIGNMENTS: true,
};
